name: Build & Test
on:
  # Triggers on PR to main
  push:
    branches: [disabled]
  pull_request:
    branches: [main]

jobs:
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn

      - name: Check Linting
        run: yarn lint

      - name: Audit Dependencies
        run: yarn run audit

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
